/** Artist-supplied biography, September 18, 2026. Preserve the approved wording. */
export function Biography() {
  return (
    <article className="bio-copy" aria-labelledby="biography-title">
      <h2 id="biography-title">Lalah Hathaway</h2>
      <p>Lalah Hathaway makes magic. She is a singer, songwriter, producer, and musician of extraordinary depth. Her rich and unmistakable voice moves effortlessly between R&B, soul, jazz, funk, and gospel. Marking a lane that is entirely her own, this five-time GRAMMY Award winner embodies the expanse of modern soul.</p>
      <p>With her new album, <em>Made in Chicago</em>, Hathaway turns her gaze toward home.</p>
      <p>Rooted in the city that shaped both her family and her musical identity, <em>Made in Chicago</em> is a deeply personal exploration of memory, place, family, and the sounds that live within us long after we leave home. The album reconnects Hathaway with Chicago not simply as a birthplace, but as a source — a city whose streets, neighborhoods, musicians, rhythms, and stories remain woven into the way she hears and creates music.</p>
      <p>As Hathaway explains, “Chicago is home. It’s where my family is from. It’s where my father’s family is from. It’s where I was born. It’s where I learned how to be a musician.” For her, the city is not simply a setting or a point of origin, but “a feeling, a sound, a way of moving through the world.” <em>Made in Chicago</em> grows from that connection — from the memories, people, and musical language that continue to shape her.</p>
      <p>Her connection to the city became the foundation for a deeply personal collection of songs about memory, family, loss, love, place, and the sounds that helped form Hathaway’s musical imagination. Rather than simply revisiting the past, <em>Made in Chicago</em> reimagines it — examining how childhood memories change as we carry them with us into adulthood.</p>
      <p>The result is an illumination, a suite of nine songs with flavors and attitudes that stand apart from any of Lalah’s previous output. “I feel these songs live at the intersection of nostalgia and melancholy,” says Lalah. “I will forever be processing the loss I suffered as a child when, in the winter of 1979, my father died at age 33. That pain is permanent. And so is the imprint his music has on mine. But MADE IN CHICAGO is not a ‘daddy album.’ It’s much more about the joyful music I heard heading into my teens. I had always taken piano lessons, but at 13 when I started attending a performing arts school, everything changed. Just those two words—<em>performing arts</em>—had me thinking differently. The world opened up.”</p>
      <p>Across <em>Made in Chicago</em>, that spirit expands into something larger: an artist at the height of her powers returning to the foundations of who she is while continuing to move fearlessly forward. “This record is about looking back without getting stuck,” Hathaway says. “It’s about honoring where I come from and understanding that it is still part of me, wherever I go.”</p>
      <p>For Hathaway, that balance between history and possibility has always been essential.</p>
      <p>Born into one of American music’s most influential families as the daughter of legendary singer and songwriter Donny Hathaway, she inherited an extraordinary musical legacy but quickly established a voice, sound, and career unmistakably her own. While studying at Berklee College of Music, Hathaway signed her first recording contract, releasing her self-titled debut album in 1990. Its breakout single, “Heaven Knows,” introduced audiences to the remarkable depth, warmth, and emotional precision that would become hallmarks of her work.</p>
      <p>In the years since, Hathaway has built a body of work that places her among the defining vocalists of her generation. Her acclaimed albums have moved comfortably between contemporary R&B, jazz, soul, and more adventurous musical territory, while her instinctive musicianship has made her an equally compelling collaborator. She has worked with a remarkable range of artists including Stevie Wonder, Prince, Herbie Hancock, Kendrick Lamar, Pharrell Williams, Robert Glasper, Anderson .Paak, Mary J. Blige, Snarky Puppy, and many others.</p>
      <p>Hathaway went on to win consecutive GRAMMY Awards for her performances of “Jesus Children,” “Little Ghetto Boy,” and “Angel,” as well as Best R&B Album for <em>Lalah Hathaway Live</em>. That live album further cemented what longtime audiences already knew: the stage is one of Hathaway’s natural homes.</p>
      <p>Her concerts are less about reproducing recordings than creating an experience in real time. Backed by musicians capable of following wherever the music leads, Hathaway can move from breathtaking intimacy to improvisation, deep-pocket soul, jazz exploration, and explosive vocal moments in the space of a single performance. It is an approach that has taken her to stages around the world, from intimate jazz rooms to major theaters, festivals, and concert halls.</p>
      <p>Hathaway's discography marks the path of a creator unafraid to play with style: ready to embrace new generations of sound and collaborators that enliven her unmistakable musical identity. Her albums ‘VANTABLACK' (2024) and ‘Honestly’ (2017) were both GRAMMY-nominated for Best R&B Album, following the win for ‘Lalah Hathaway Live’ (2015) in the category. Her catalogue touches the disparate corners of R&B, Soul and beyond, delivering a spellbinding breadth effortlessly.</p>
      <p><em>Made in Chicago</em> brings that journey home.</p>
      <p>It is the work of an artist who understands where she comes from without being confined by it: daughter and innovator, historian and futurist, vocalist and musician, interpreter and songwriter. More than three decades into her career, Lalah Hathaway remains one of contemporary music’s most compelling voices — carrying the tradition of soul forward not by preserving it in place, but by continually discovering what else it can become.</p>
    </article>
  );
}
